# Generated by Django 3.2 on 2021-04-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210420_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='security',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
