# Generated by Django 3.2 on 2021-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('order', '0003_auto_20210421_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendors',
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ManyToManyField(related_name='orders', to='vendor.Vendor'),
        ),
    ]
