# Generated by Django 3.2 on 2021-04-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vendor',
            new_name='vendors',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
    ]
