# Generated by Django 3.2 on 2021-04-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('order', '0006_auto_20210421_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='vendor.vendor'),
            preserve_default=False,
        ),
    ]
