# Generated by Django 3.2 on 2021-04-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='security_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
